model:
  model_path: /path/to/LingBot-VLA-Depth
  tokenizer_path: /path/to/Qwen2.5-VL-3B-Instruct/

data:
  datasets_type: vla
  train_path: /path/to/mixed_robotwin_5tasks
  norm_path: assets/norm_stats/robotwin_5_custom.json

train:
  global_batch_size: 512
  output_dir: output/norm